import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import JokeService from '../services/services'
export default function Home() {
  const [titleButton, setTitleButton] = React.useState("Load Jokes")
  const [jokesData, SetJokesData] = React.useState({})

  const getJokesHandler = () => {
    JokeService.getJokes().then(res => {
      setTitleButton("Next Jokes")
      SetJokesData(res?.data)
    })
      .catch(err => console.log(err))
  }

  const clearJokes = () => {
    setTitleButton("Load Jokes")
    SetJokesData({})
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to chuck norris jokes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <h2>Jokes si Chuck Norris</h2>
        <code>API : https://api.chucknorris.io/jokes/random</code>
        <br/>
        <br/>

        {
          jokesData?.value === null ?
            <h3></h3> : <h3 style={{backgroundColor:"blue"}}>{jokesData?.value}</h3>
        }
        <button onClick={() => getJokesHandler()}>{titleButton}</button>
        <br/>
        <button onClick={() => clearJokes()}>Clear Jokes</button>
      

    </div>
  )
}
